config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|fr/ do
    root 'static_pages#home'
    get 'static_pages/home'
    get 'static_pages/about'
    get 'static_pages/help'
    post 'sessions/login'
    get 'sessions/logout'
    resources :readers, only: [:index, :show, :create, :update, :destroy]
    resources :books, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: [:index, :show, :create, :update, :destroy]
    post 'books/:book_id' => "books#lend"
    get 'complete_from_isbn' => "books#complete_from_isbn"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<%= render "sessions/login_form" %>

<nav>
  <%=link_to t(".home"), "/" %>
  <% if @current_user %>
    <%=link_to t(".books"), books_path %>
    <%=link_to t(".readers"), readers_path %>
    <% if @current_user&.admin? %>
      <%=link_to t(".users"), users_path %>
    <%else%>
      <%=link_to t(".myaccount"), "/users/#{@current_user.id}" %>  
    <% end %>
  <% end %>
  <%=link_to t(".help"), "/static_pages/help" %>
  <%=link_to t(".about"), "/static_pages/about" %>
  <% if @current_user %>
    <%=link_to t(".logout"), "/sessions/logout" %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yalm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%if flash[:info] %>
      <div class="alert" role="alert"><%= flash[:info]%></div>
    <%end%>
    <header>
         <%= render "layouts/header"%>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>